headersOrigin = "config"
redirects = []

[functions]

[functions."*"]

[[plugins]]
origin = "default"
package = "@netlify/plugin-nextjs"

[plugins.inputs]

[build]
publish = "C:\\Users\\Administrator\\discover-website\\payduty-deploy"
publishOrigin = "config"
commandOrigin = "ui"
base = "C:\\Users\\Administrator\\discover-website\\payduty-deploy"
command = "yarn run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"